Monkey.Mvc/Controllers/CollectionController.cs
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Monkey.Domain;
using Monkey.Mvc.Domain;
using Monkey.Mvc.Models;

namespace Monkey.Mvc.Controllers
{

  [Authorize]
  public class CollectionController : Controller
    {

      private readonly ICollectionRepository _collectionRepository;

      private readonly IFactory<Figure, FigureModel> _figureModelFactory;

      private readonly IFactory<FigureModel, Figure> _figureFactory;

    private readonly IFileUploader _fileUploader;

      public CollectionController(ICollectionRepository collectionRepository, IFactory<Figure, FigureModel> figureModelFactory, IFactory<FigureModel, Figure> figureFactory, IFileUploader fileUploader)
      {
        _collectionRepository = collectionRepository;
        _figureModelFactory = figureModelFactory;
        _figureFactory = figureFactory;
        _fileUploader = fileUploader;
      }


  // GET: Collection
    public ActionResult Index()
    {
      var model = (from figure in _collectionRepository.List() select _figureModelFactory.Create(figure)).ToList();
      return View(model);
    }

    [HttpGet]
    public ActionResult Details(int id)
    {
      var model = _collectionRepository.Fetch(id);
      return PartialView(_figureModelFactory.Create(model));
    }
    [HttpGet]
    public ActionResult Edit(int id)
    {
      var figure = _collectionRepository.Fetch(id);

      return View(_figureModelFactory.Create(figure));
    }

    [HttpPost]
    public ActionResult Edit(FigureModel model)
    {
      if (ModelState.IsValid)
      {
        try
        {
            var newImage = _fileUploader.Upload(model.File);
            model.ImageName = string.IsNullOrEmpty(newImage) ? model.ImageName : newImage;
        }
        catch (IOException exception)
        {
          ModelState.AddModelError("File", exception.Message);
        }

        if (ModelState.IsValid)
        {
          _collectionRepository.Update(_figureFactory.Create(model));

          return RedirectToAction("Index");
        }
      }

      return View(model);
    }


    [HttpGet]
      public ActionResult Create()
      {
      return View(new FigureModel());
    }

    [HttpPost]
    public ActionResult Create(FigureModel model)
    {

      if (ModelState.IsValid)
      {
        try
        {
          var newImage = _fileUploader.Upload(model.File);
          model.ImageName = string.IsNullOrEmpty(newImage) ? model.ImageName : newImage;
        }
        catch (IOException exception)
        {
          ModelState.AddModelError("File", exception.Message);
        }
   
        if (ModelState.IsValid)
        {
          _collectionRepository.Create(_figureFactory.Create(model));

          return RedirectToAction("Index");
        }
      }
      return View(model);
    }

    public ActionResult Delete(int id)
    {
      if (id == 0)
      {
        return RedirectToAction("Index");
      }

      _collectionRepository.Delete(id);

      return RedirectToAction("Index");
    }
  

  }
}

Monkey.Mvc/Views/Collection/Create.cshtml
@model Monkey.Mvc.Models.FigureModel

@{
    ViewBag.Title = "Samling - Opret figur";
}

<section class="featured">
    <div class="content-wrapper">
        <hgroup class="title">
            <h1>Opret figur</h1>
        </hgroup>
    </div>
</section>
<section class="main-content clear-fix">

    @using (Html.BeginForm("Create", "Collection", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Opret figur</h4>
        <hr />
        @Html.Partial("_EditItem", @Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group btn-group-md">
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-save"></span>Gem</button>
                    <a href="@Url.Action("Index")" class="btn btn-default"><span class="glyphicon glyphicon-list"></span>Tilbage til oversigt</a>
                </div>

            </div>
        </div>
    </div>
    }

    <div>

    </div>
</section>

Monkey.Mvc/Views/Collection/Details.cshtml
@model Monkey.Mvc.Models.FigureModel

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Remark)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Remark)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BoughtDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BoughtDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SoldFor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoldFor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BoughtAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BoughtAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Material)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Material)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dd>
            <img src="/Images/Figures/@Model.ImageName" class="details" />
        </dd>
    </dl>
</div>

Monkey.Mvc/Views/Collection/Edit.cshtml
@model Monkey.Mvc.Models.FigureModel

@{
    ViewBag.Title = "Samling - Ret figur";
}

<section class="featured">
    <div class="content-wrapper">
        <hgroup class="title">
            <h1>Ret figur</h1>
        </hgroup>
    </div>
</section>
<section class="main-content clear-fix">

@using (Html.BeginForm("Edit", "Collection", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @Html.Partial("_EditItem", @Model)

        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <div class="btn-group btn-group-sm">
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-save"></span>Gem</button>
                    <a href="@Url.Action("Index")" class="btn btn-default"><span class="glyphicon glyphicon-list"></span>Tilbage til oversigt</a>
                </div>
            </div>
        </div>
    </div>
    }
</section>


Monkey.Mvc/Views/Collection/Index.cshtml
@using Monkey.Mvc.Models
@model IEnumerable<FigureModel>

@{
    ViewBag.Title = "Oversigt";
}
  
<div class="panel-heading"><h1>Oversigt</h1></div>
<div class="panel-body">
  <p>
      <a href="@Url.Action("Create")" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span>Opret</a>        
  </p>
  @foreach (var item in Model)
  {
      Html.RenderPartial("_ListItem", item);
  }

</div>

@{Html.RenderPartial("_Modal", new ActionModel {Action = "Details", Controller = "Collection"});}

@section scripts{
    <script src="~/Scripts/App/Viewer.js"></script>
}



Monkey.Mvc/Views/Collection/_EditItem.cshtml
@model Monkey.Mvc.Models.FigureModel

@Html.ValidationSummary(true, "", new { @class = "text-danger" })

@Html.HiddenFor(model => model.ImageName)

<div class="form-group">
    @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control", @autofocus = "autofocus" } })
        @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.BoughtDate, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.BoughtDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.BoughtDate, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Material, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Material, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Material, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.BoughtAt, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.BoughtAt, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.BoughtAt, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control small", @type = "number" } })
        @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Length, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Length, new { htmlAttributes = new { @class = "form-control small", @type = "number" } })
        @Html.ValidationMessageFor(model => model.Length, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control small", @type = "number" } })
        @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        <input type="file" id="File" name="File" class="form-control" />
        @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
    </div>
</div>


Monkey.Mvc/Views/Collection/_ListItem.cshtml
@model Monkey.Mvc.Models.FigureModel

<div class="itemHolder">
    <div class="col-md-6">
        <div style="padding-right: 20px;">
            <img src="/Images/Figures/index/@Model.ImageName" class="index" data-toogle="modal" data-target="#modalDetails" />
        </div>
    </div>
    <div class="col-md-6">
            <ul class="field-list">
                <li>
                    <label>@Html.DisplayNameFor(model => model.Id)</label>
                    <div>@Html.DisplayFor(modelItem => Model.Id)</div>
                </li>
                <li>
                    <label>@Html.DisplayNameFor(model => model.BoughtDate)</label>
                    <div>
                        @if (@Model.BoughtDate.HasValue)
                        {
                          @Model.BoughtDate.Value.ToString("dd-MM-yyyy")
                        }
                    </div>
                </li>
                <li>
                    <label>@Html.DisplayNameFor(model => model.Price)</label>
                    <div>@Html.DisplayFor(modelItem => Model.Price)</div>
                </li>
                @if (Model.SoldFor > 0)
                {
                    <li>
                        <div class="sold">Solgt</div>
                    </li>
                }
                <li>
                    <label></label>
                    <div></div>
                </li>
                <li>
                    <label></label>
                    <div></div>
                </li>
                <li>
                    <label></label>
                    <div class="btn-group btn-group-sm">
                        <a href='@string.Format("javascript:Viewer.getMonkey({0})", Model.Id)' class="btn btn-default"><span class="glyphicon glyphicon-eye-open"></span>Detaljer</a>
                        <a href="@Url.Action("Edit", new {id = Model.Id})" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span>Ret</a>
                        <a href="@Url.Action("Delete", new {id = Model.Id})" class="btn btn-default" onclick="return confirm('Er du sikker på at figur skal slettes ?');"><span class="glyphicon glyphicon-trash"></span>Slet</a>
                     </div>

                </li>
            </ul>
        </div>
</div>
