MonkeyMvc/Controllers/MonkeyController.cs
using System.IO;
using Monkey.Domain;
using MonkeyMvc.Models;
using System.Linq;
using System.Web.Http;
using System.Web.Mvc;
using MonkeyMvc.Domain;


namespace MonkeyMvc.Controllers
{
  public class MonkeyController : Controller
  {


     private readonly IFigureRepository _figureRepository;

     private readonly IFactory<Figure, FigureModel>_figureModelFactory;

    private readonly IFactory<FigureModel, Figure> _figureFactory; 

    private readonly IFilterService<Figure> _filterService;

    private readonly IFileUploader _fileUploader;


    public MonkeyController(IFigureRepository figureRepository, IFactory<Figure, FigureModel> figureModelFactory, IFilterService<Figure> filterService, IFactory<FigureModel, Figure> figureFactory, IFileUploader fileUploader)
    {
      _figureRepository = figureRepository;
      _figureModelFactory = figureModelFactory;
      _filterService = filterService;
      _figureFactory = figureFactory;
      _fileUploader = fileUploader;
    }

    [System.Web.Mvc.HttpGet]
    public ActionResult Edit(int id)
    {
            var model = (from figure in _figureRepository.List() where figure.Id==id select _figureModelFactory.Create(figure)).FirstOrDefault();
            return View(model);

    }

    public ActionResult Delete(int id)
    {
      _figureRepository.Delete(id);
      return RedirectToAction("Index");

    }


    [System.Web.Mvc.HttpPost]
    public ActionResult Edit(FigureModel model)
    {
      if (ModelState.IsValid)
      {
        try
        {
          var newImage = _fileUploader.Upload(model.File);
          model.ImageName = string.IsNullOrEmpty(newImage) ? model.ImageName : newImage;
        }
        catch (IOException exception)
        {
          ModelState.AddModelError("File", exception.Message);
        }



        _figureRepository.Update(_figureFactory.Create(model));
        return RedirectToAction("Index");
      }
      
      return View(model);
    }

   


    [System.Web.Mvc.HttpPost]
    public ActionResult Search(string searchTerm)
    {
      var model = (from figure in _filterService.Filter(_figureRepository.List())
        where figure.Remark.ToLower().Contains(searchTerm.ToLower())
        select _figureModelFactory.Create(figure)).ToList();
      return View(model);
    }

    [System.Web.Mvc.HttpGet]
    public ActionResult Search([FromUri]string searchTerm, string dummy)
    {
      var model = (from figure in _filterService.Filter(_figureRepository.List())
                   where string.IsNullOrEmpty(searchTerm) 
                   || figure.Remark.ToLower().Contains(searchTerm.ToLower())
                   || (figure.Material != null && figure.Material.ToLower().Contains(searchTerm.ToLower()))
                   select _figureModelFactory.Create(figure)).ToList();
      return View(model);
    }
    public ActionResult Index()
    {
            var model = new MonkeyModel()
            {
                Figures = (from figure in _filterService.Filter(_figureRepository.List())
                           select _figureModelFactory.Create(figure)).ToList()
            } ;

      return View(model);
    }

    [System.Web.Mvc.HttpGet]
    public ActionResult Details(int id)
    {
      var model = _figureRepository.Fetch(id); 
      return PartialView(_figureModelFactory.Create(model));
    }

  }
}

MonkeyMvc/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Monkey.Domain;
using MonkeyMvc.Models;

namespace MonkeyMvc.Controllers
{
    public class UserController : Controller
    {

      private IUserRepository userRepository;

      public UserController(IUserRepository userRepository)
      {
        this.userRepository = userRepository;
      }

      // GET: User
        public ActionResult Index()
        {
            return View();
        }

      [HttpGet]
      public ActionResult LogIn()
      {
        return View();
      }

      public ActionResult LogOut()
      {
        FormsAuthentication.SignOut();
        return RedirectToAction("Index", "Home");
      }

    [HttpPost]
    public ActionResult LogIn(UserModel user)
    {
      if (ModelState.IsValid)
      {
        if (IsValid(user.Email, user.Password))
        {
          FormsAuthentication.SetAuthCookie(user.Email, false);
          return RedirectToAction("Index", "Home");
        }
        ModelState.AddModelError("Email", "Login data is incorrect");
      }
      return View(user);
    }


      private bool IsValid(string email, string password)
      {
        
        bool isValid = false;

        var user = userRepository.List().FirstOrDefault(c => c.Email == email);

        if (user != null)
        {
          isValid = user.Password == password;
        }

        return isValid;
        
      }

  }
}

MonkeyMvc/Views/Shared/_FigureDetails.cshtml
@model MonkeyMvc.Models.FigureModel

<div>
    <h4>Figure</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Remark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Material)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Material)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BoughtAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BoughtAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoldFor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoldFor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalesPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalesPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ForSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ForSale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            <img src="@Model.ImageName" class="index"/>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MonkeyMvc/Views/Shared/_Header.cshtml
<header>
    <div class="content-wrapper">
        <div class="float-left">
            <p class="site-title">
                <a href="~/">ASP.NET Web API</a>
            </p>
        </div>
        <div class="float-right">
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("MVC", "Index", "Monkey", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Collection", "Index", "Collection", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Angular", "Index", "Angular", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Figure", "API", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Help", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </nav>
        </div>
    </div>
</header>

MonkeyMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/modernizr")

    @if (!Request.IsLocal && Request.ServerVariables["REMOTE_ADDR"] != "5.103.74.145")
    {
        <script type="text/javascript">
            var appInsights=window.appInsights||function(config){
                function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
            }({
                instrumentationKey: "614dbdeb-1b63-4103-b1e3-96d1930d2ff0",
                sessionRenewalMs: 3600000,
                sessionExpirationMs: 172800000
            });

            window.appInsights=appInsights;
            appInsights.trackPageView();
        </script>
    }
 
</head>
<body>
<div class="container">
@Html.Partial("_Menu")    
</div>

<div class="container">
    <div id="body">
        @RenderBody()
    </div>
</div>

 @Scripts.Render("~/bundles/jquery")
 @Scripts.Render("~/bundles/bootstrap")
 @RenderSection("scripts", required: false)
</body>
</html>

MonkeyMvc/Views/Shared/_Menu.cshtml
<header>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><img src="/Images/logo.png" class="logo" /></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Forside", "Index", "Home", new {}, null)</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Til salg<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Liste", "Index", "Monkey", new {area = ""}, null)</li>
                            <li>@Html.ActionLink("Ikke se ikke høre ikke tale", "Search", "Monkey", new {searchTerm = "Ikke"}, null)</li>
                            <li>@Html.ActionLink("Fedtsten", "Search", "Monkey", new {searchTerm = "Fedtsten"}, null)</li>
                        </ul>
                    </li>
                    @if (Request.IsAuthenticated)
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Samling<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Liste", "Index", "Collection", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Opret figur", "Create", "Collection", new { area = "" }, null)</li>
                        </ul>
                    </li>

                    }
                    </ul>
                <form action="/monkey/search" method="POST" role="search" class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" id="searchTerm" name="searchTerm" class="form-control" placeholder="Søg" />
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-search"></span>Søg</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    @if (Request.IsAuthenticated)
                    {
                        <li>
                            <p class="navbar-text">
                                @Html.Encode(User.Identity.Name)                                
                            </p>
                        </li>
                        <li>@Html.ActionLink("Logout", "LogOut", "User", new {area = ""}, null)</li>
    
                    }
                    else
                    {
                    <li>@Html.ActionLink("Login", "LogIn", "User", new { area = "" }, null)</li>
                    }


 
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>    
</header>

MonkeyMvc/Views/Shared/_Modal.cshtml
@model MonkeyMvc.Models.ActionModel

<div id="modalDetails" class="modal fade" role="dialog" data-url='@Url.Action(Model.Action, Model.Controller)'>
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Detaljer</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal"><span class="glyphicon glyphicon-eye-close"></span>Luk</button>
            </div>
        </div>
    </div>
</div>
